[package]
name = "stranger_char"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
opt-level = 3         # ou "3" para máxima otimização
lto = true
codegen-units = 1
panic = "abort"
